version: "3.6"
services:
  server:
    image: "${REGISTRY}/${SERVICE}:${TAG}"
    networks:
      - monitoring
      - default
    deploy:
      replicas: ${REPLICA}
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 4096M
      placement:
        constraints:
          - node.labels.monitor!=1
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 3s
      retries: 1
      start_period: 10s

networks:
  monitoring:
    external:
      name: monitoring
   