version: "3"
services:
  server:
    image: "${REGISTRY}/plantuml-server:${TAG}"
    deploy:
      replicas: ${REPLICA}
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8080"
    networks:
      - webnet
networks:
  webnet:
   