version: "3.4"
services:
  server:
    image: "${REGISTRY}/${SERVICE}:${TAG}"
    deploy:
      replicas: ${REPLICA}
      restart_policy:
        condition: on-failure
    ports:
      - "8081:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 3s
      retries: 1
      start_period: 10s

   